/**
 * The text lines (`pdfTextLines`) of two GLS compensation letters, as read
 * on 2026-09-29. Only the company's own name and GLS's address are in them.
 */
export const GLS_COMPENSATION_0827_LINES: readonly string[] = [
  "GLS General Logistics System Hungary",
  "100031291 ACROPORA KFT.",
  "Csomag-Logisztikai Kft.",
  "2351 Alsónémedi",
  "Email: info@acropora.hu",
  "GLS-Európa u. 2.",
  "Telefon: +3629-886-670",
  "Telefax: +3629-886-627",
  "Internet: www.gls-hungary.com",
  "KOMPENZÁCIÓS ÉRTESÍTŐ (COMPENSATION LETTER)",
  "Ezúton tájékoztatjuk, hogy az Önökkel kötött szerződés és a GLS Általános Üzleti Feltételek 14. pontja alapján,",
  "az alábbi utánvét összegeket kompenzáltuk be a mai napon:",
  "(We would like to inform you that under the agreement entered into with you and based on",
  "General Terms and Conditions of the GLS Hungary, the following amount were compensated today:)",
  "Utánvét | Kompenzálás | Utalt UV | Számlaszám/ | Számla össz./ UV tartozás | Maradvány",
  "Ügyfélszám | Dátum",
  "Név (Name) | (COD) | (Compensation) | (Transferred | Csomagszám | (Invoice amount/ COD debt) | (Remaning)",
  "(Client nr.) | (Date)",
  "(HUF) | (HUF) | COD) (HUF) | (Invoice nr./ Parcel nr.) | (HUF) | (HUF)",
  "HU00905612,",
  "ACROPORA",
  "3480031291 | 6 950 | 6 950 | 0 | HU00898334, | 14 963 | 8 013 2026.08.27",
  "KFT.",
  "HU00912382",
  "Alsónémedi, 2026.08.27",
  "=== oldal vege ===",
];

export const GLS_COMPENSATION_0910_LINES: readonly string[] = [
  "GLS General Logistics System Hungary",
  "100031291 ACROPORA KFT.",
  "Csomag-Logisztikai Kft.",
  "2351 Alsónémedi",
  "Email: info@acropora.hu",
  "GLS-Európa u. 2.",
  "Telefon: +3629-886-670",
  "Telefax: +3629-886-627",
  "Internet: www.gls-hungary.com",
  "KOMPENZÁCIÓS ÉRTESÍTŐ (COMPENSATION LETTER)",
  "Ezúton tájékoztatjuk, hogy az Önökkel kötött szerződés és a GLS Általános Üzleti Feltételek 14. pontja alapján,",
  "az alábbi utánvét összegeket kompenzáltuk be a mai napon:",
  "(We would like to inform you that under the agreement entered into with you and based on",
  "General Terms and Conditions of the GLS Hungary, the following amount were compensated today:)",
  "Utánvét | Kompenzálás | Utalt UV | Számlaszám/ | Számla össz./ UV tartozás | Maradvány",
  "Ügyfélszám | Dátum",
  "Név (Name) | (COD) | (Compensation) | (Transferred | Csomagszám | (Invoice amount/ COD debt) | (Remaning)",
  "(Client nr.) | (Date)",
  "(HUF) | (HUF) | COD) (HUF) | (Invoice nr./ Parcel nr.) | (HUF) | (HUF)",
  "ACROPORA",
  "3480031291 | 28 900 | 18 111 | 10 789 HU00920611 | 18 111 | 0 2026.09.10",
  "KFT.",
  "Alsónémedi, 2026.09.10",
  "=== oldal vege ===",
];
