export { Prisma, PrismaClient } from "@prisma/client";
export type {
  AuditLog,
  Aquarium,
  AquariumMeasurement,
  Asset,
  AssetDocument,
  AssetDocumentType,
  AssetEvent,
  Brand,
  Category,
  ChannelListing,
  Customer,
  CustomerAddress,
  DomainEvent,
  ExternalReference,
  FoxpostMonthlyReport,
  FoxpostResolutionSource,
  FoxpostSettlement,
  FoxpostSettlementLine,
  FoxpostSettlementLineStatus,
  FoxpostSettlementStatus,
  FoxpostSyncRun,
  FoxpostSyncRunStatus,
  GoodsReceipt,
  GoodsReceiptLine,
  IcpReport,
  IcpResult,
  Product,
  ProductCategory,
  ProductImage,
  ProductRelation,
  ProductVariant,
  PurchaseInvoice,
  PurchaseInvoiceLine,
  PurchaseInvoiceSource,
  PurchaseInvoiceStatus,
  PurchaseOrder,
  PurchaseOrderLine,
  SalesOrder,
  SalesOrderLine,
  ServiceJob,
  ServiceJobAsset,
  ServiceToken,
  Session,
  StockMovement,
  StockMovementLine,
  Supplier,
  SupplierProduct,
  Task,
  TaskSource,
  TaskStatus,
  User,
  UserRole,
  Warehouse,
  WarehouseLocation,
  Worksheet,
  WorksheetDepartment,
  WorksheetLine,
  WorksheetNumberSequence,
  WorksheetSignatureDecision,
  WorksheetVersion,
  WorksheetVersionSignature,
  WorksheetVersionStatus,
} from "@prisma/client";

export { prisma } from "./database.js";
export type { DatabaseClient } from "./database.js";
export { checkDatabaseHealth } from "./database-health.js";
export type {
  DatabaseHealth,
  DatabaseHealthClient,
} from "./database-health.js";
export { Repository } from "./repository.js";
export { seedBrands, seedCategories, seedUsers } from "./seed-data.js";
